module.exports = [`
    type Contact {
      name: String!
      email: String!
      phone: String
      photo: String
      typeRacing: TypeRacing
    }

    extend type Query {
      # Contact with type racing data
      contacts: [Contact]
    }

`];
