module.exports = [`

  # Allowed queries:
  type Query {
    # A simple type for getting started!
    rootHello: String

    # Basic contact
    contacts: [Contact]

    # Type Racing Data
    typeRacing(id: ID!): TypeRacing
  }

  schema {
    query: Query
  }

`];
