module.exports = [`

  # Type Racing Data
  type TypeRacing {
    email: String!
    score: Int!
    nationality: String!
  }

  extend type Query {
    # Type Racing Data
    typeRacing(email: String!): TypeRacing
  }

`]
